### ISSUE TITLE
emmeans support

### ISSUE THREAD

**Issue by rvlenth** [georgheinze/logistf#51]
Hello,

A user has requested support for `logistf` models in the **emmeans** package. See https://github.com/rvlenth/emmeans/issues/395

It is best for developers to incorporate emmeans support for their models, as they know the finer details and better understand what might be important/appropriate. There is quite a bit of documentation for how to do this at https://cran.r-project.org/web/packages/emmeans/vignettes/xtending.html. It basically involves writing a method for recovering the data and another one that is similar to the `predict()` method, with appropriate options. Then there is a simple addition to `onLoad()` that will register these methods.

It appears that it would be pretty easy to do, as the `emmeans::qdrg()` function already seemed to work well and produce usable results. Let me know if you have questions.

**Comment by gregorsteiner** [comment]
Hello,

thanks for bringing this to our attention. I implemented `recover_data` and `emm_basis` methods for `logistf` objects. `emmeans::emmeans` should now work with `logistf` objects.

**Comment by rvlenth** [comment]
Hello,

I wanted to see how it does, so I tried installing the package from GitHub, but it still doesn't have the emmeans stuff. Have you merged your PR?

**Comment by rvlenth** [comment]
Thanks. Looks good to me. I tried the first example for `logistf`:
```
> emmeans(fit, ~age+dia)
 age dia emmean    SE  df lower.CL upper.CL
   0   0  -0.23 0.184 232  -0.5924    0.133
   1   0  -1.34 0.408 232  -2.1387   -0.532
   0   1   2.87 1.498 232  -0.0852    5.818
   1   1   1.76 1.495 232  -1.1841    4.705

Results are averaged over the levels of: oc, vic, vicl, vis 
Results are given on the logit (not the response) scale. 
Confidence level used: 0.95 
```
Compared to using `glm`:
```
> fit.glm = glm(case ~ age+oc+vic+vicl+vis+dia, data=sex2, family=binomial)
> emmeans(fit.glm, ~age+dia)
 age dia emmean      SE  df asymp.LCL asymp.UCL
   0   0 -0.239   0.188 Inf    -0.606     0.129
   1   0 -1.403   0.428 Inf    -2.241    -0.565
   0   1 16.496 799.425 Inf -1550.349  1583.340
   1   1 15.331 799.425 Inf -1551.513  1582.176

Results are averaged over the levels of: oc, vic, vicl, vis 
Results are given on the logit (not the response) scale. 
Confidence level used: 0.95 
```
Those cases with `dia = 1` are much more pleasant using `logistf`!

**Comment by rvlenth** [comment]
PS - I added an entry for `logistf` in the **emmeans** "models" vignette indicating that support is provided in your package. That will show up with the next CRAN update, maybe in a month, or later than that.

**Comment by andreasleha** [comment]
Great!  Thanks a lot for your effort!

**Comment by rvlenth** [comment]
Just a comment: I noticed that the functions `recover_data.logistf` and `emm_basis.logistf` are exported and documented. Those functions are not intended for users, so in someways, this can create confusion. And also, it should not be necessary to even export them, as the methods are registered by `.onLoad()`, and `emmeans()` should "just work" with `logistf` objects. 

I might suggest that instead you creat a help page titled, say, `emmeans-logistf` that just states that the support is available and gives an example of using `emmeans()` with a `logistf` fitted model.

**Comment by gregorsteiner** [comment]
Done! I will merge the PR later today and it will be on CRAN with the next update. @rvlenth Thanks a lot for your help!
